### ISSUE TITLE
UInt64::toString may return wrong result

### ISSUE THREAD

**Issue by Klug76** [Atry/protoc-gen-as3#48]
UInt64::toString(n != 10) may return wrong result, e.g. UInt64.fromNumber(4294967296).toString(16) return 100000006 instead of 100000000.
Problem in Binary64::div (row 44):
const mod:uint = (low % n + modHigh * 6) % n
(error in the formula)

**Comment by Atry** [comment]
>
``` actionscript3
const mod:uint = (low % n + modHigh * 6) % n
```

I use 6 because `4294967296.0 % 10` is 6

I guess it should be

``` actionscript3
const mod:uint = (low % n + modHigh * uint(4294967296.0 % n)) % n
```
