### ISSUE TITLE
当一个字段是String,同时又为null时，会报错

### ISSUE THREAD

**Issue by asheigithub** [Atry/protoc-gen-as3#55]
当一个字段是String,同时又为null时，序列化时报错。我研究下来，当字段为null时就跳过这个tag,于是我这么修改:
         public static function write_TYPE_STRING(output:WritingBuffer, value:String):void {
			if (value == null)
			{
				--output.position;	//吃掉前面的tag
				return; 
			}
			const i:uint = output.beginBlock()
			//if (value != null)
			{
				output.writeUTFBytes(value);
			}
			//else
			//{
				//output.writeShort(0);
			//}
			output.endBlock(i)
		}

请问作者这么修改正确吗我这么改后测试好像正确

**Comment by Atry** [comment]
如果你想问问题，你可以用StackOverflow。

**Comment by asheigithub** [comment]
我不是光想问问题，我是直接告诉你这里有异常，并且这样改可以解决。只是不完全确定这样改是否正确。

**Comment by Atry** [comment]
如果报告bug，请包含以下内容：

1. 能最小重现bug的完整代码
2. 你期待的运行结果或者输出
3. 你看到的运行结果或者输出
